'use strict';

const Knex = require('knex');
const envy = require('envy');
const env = envy();

const knex = Knex({
    client: 'mysql',
    debug: true,
    log: {
        warn(message) {
            console.log('WARN',message);
        },
        error(message) {
            console.log('ERROR',message);
        },
        deprecate(message) {
            console.log('DEPRICATE',message);
        },
        debug(message) {
            console.log('DEBUG',message);
        },
    },
    connection: {
        host: env.dbHost,
        port: 3306,
        user: env.dbUsername,
        password: env.dbPassword,
        database: env.dbName,
        dateStrings: true,
        multipleStatements: true
    },
    pool: {
        min: 2,
        max: 2,
       // createTimeoutMillis: 3000,
       // acquireTimeoutMillis: 10000,
       // idleTimeoutMillis: 500,
       // reapIntervalMillis: 500,
       // createRetryIntervalMillis: 100,
       // propagateCreateError: true // <- default is true, set to false
    },
    acquireConnectionTimeout: 10000
});




knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))')
    .catch((err) => console.error('Expected1', err))
    .then(() => knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))'))
    .catch((err) => console.error('Expected2', err))
// .then(() => process.exit(0));


knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))')
    .catch((err) => console.error('Expected1', err))
    .then(() => knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))'))
    .catch((err) => console.error('Expected2', err));


knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))')
    .catch((err) => console.error('Expected1', err))
    .then(() => knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))'))
    .catch((err) => console.error('Expected2', err));

knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))')
    .catch((err) => console.error('Expected1', err))
    .then(() => knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))'))
    .catch((err) => console.error('Expected2', err));

knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))')
    .catch((err) => console.error('Expected1', err))
    .then(() => knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))'))
    .catch((err) => console.error('Expected2', err));

knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))')
    .catch((err) => console.error('Expected1', err))
    .then(() => knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))'))
    .catch((err) => console.error('Expected2', err));

knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))')
    .catch((err) => console.error('Expected1', err))
    .then(() => knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))'))
    .catch((err) => console.error('Expected2', err));

knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))')
    .catch((err) => console.error('Expected1', err))
    .then(() => knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))'))
    .catch((err) => console.error('Expected2', err));

knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))')
    .catch((err) => console.error('Expected1', err))
    .then(() => knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))'))
    .catch((err) => console.error('Expected2', err));
knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))')
    .catch((err) => console.error('Expected1', err))
    .then(() => knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))'))
    .catch((err) => console.error('Expected2', err));
knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))')
    .catch((err) => console.error('Expected1', err))
    .then(() => knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))'))
    .catch((err) => console.error('Expected2', err));
knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))')
    .catch((err) => console.error('Expected1', err))
    .then(() => knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))'))
    .catch((err) => console.error('Expected2', err));
knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))')
    .catch((err) => console.error('Expected1', err))
    .then(() => knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))'))
    .catch((err) => console.error('Expected2', err));
knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))')
    .catch((err) => console.error('Expected1', err))
    .then(() => knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))'))
    .catch((err) => console.error('Expected2', err));
knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))')
    .catch((err) => console.error('Expected1', err))
    .then(() => knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))'))
    .catch((err) => console.error('Expected2', err));
knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))')
    .catch((err) => console.error('Expected1', err))
    .then(() => knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))'))
    .catch((err) => console.error('Expected2', err));
knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))')
    .catch((err) => console.error('Expected1', err))
    .then(() => knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))'))
    .catch((err) => console.error('Expected2', err));
knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))')
    .catch((err) => console.error('Expected1', err))
    .then(() => knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))'))
    .catch((err) => console.error('Expected2', err));
knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))')
    .catch((err) => console.error('Expected1', err))
    .then(() => knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))'))
    .catch((err) => console.error('Expected2', err));
knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))')
    .catch((err) => console.error('Expected1', err))
    .then(() => knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))'))
    .catch((err) => console.error('Expected2', err));
knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))')
    .catch((err) => console.error('Expected1', err))
    .then(() => knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))'))
    .catch((err) => console.error('Expected2', err));
knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))')
    .catch((err) => console.error('Expected1', err))
    .then(() => knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))'))
    .catch((err) => console.error('Expected2', err));
knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))')
    .catch((err) => console.error('Expected1', err))
    .then(() => knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))'))
    .catch((err) => console.error('Expected2', err));
knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))')
    .catch((err) => console.error('Expected1', err))
    .then(() => knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))'))
    .catch((err) => console.error('Expected2', err));
knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))')
    .catch((err) => console.error('Expected1', err))
    .then(() => knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))'))
    .catch((err) => console.error('Expected2', err));
knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))')
    .catch((err) => console.error('Expected1', err))
    .then(() => knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))'))
    .catch((err) => console.error('Expected2', err));
knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))')
    .catch((err) => console.error('Expected1', err))
    .then(() => knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))'))
    .catch((err) => console.error('Expected2', err));
knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))')
    .catch((err) => console.error('Expected1', err))
    .then(() => knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))'))
    .catch((err) => console.error('Expected2', err));
knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))')
    .catch((err) => console.error('Expected1', err))
    .then(() => knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))'))
    .catch((err) => console.error('Expected2', err));
knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))')
    .catch((err) => console.error('Expected1', err))
    .then(() => knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))'))
    .catch((err) => console.error('Expected2', err));
knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))')
    .catch((err) => console.error('Expected1', err))
    .then(() => knex.raw('select count(*) as `totalCount` from `person` left join `address` as `person-address` on `person`.`address_id` = `person-address`.`id` left join `state` as `person-address-state` on `person-address`.`state_id` = `person-address-state`.`id` where `person`.`created` <= CURRENT_TIMESTAMP(6) and `person`.`expired` > CURRENT_TIMESTAMP(6) and not `person`.`is_unsynced` = 1 and IF(`person-address`.id IS NULL, TRUE, `person-address`.created <= CURRENT_TIMESTAMP(6)) and IF(`person-address`.id IS NULL, TRUE, `person-address`.expired > CURRENT_TIMESTAMP(6))'))
    .catch((err) => console.error('Expected2', err));



